name: gather-mst-info-manual
on: 
  workflow_dispatch:
    
jobs: 
  scrape-and-save:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.1.0'
      - run: npm i
      - run: node scraper/scraper.js

      - uses: EndBug/add-and-commit@v9
        with:
          message: Updated json
          committer_name: GitHub Actions
          committer_email: actions@github.com